[package]
name = "syscall_test"
version = "0.0.0"
authors = ["Ivor Wanders <ivor@iwanders.net>"]

# Disables error handling, prevents eh_personality requirement.
[profile.dev]
panic = "abort"
[profile.release]
panic = "abort"

