[package]
name = "test"
version = "0.0.0"
authors = ["Ivor Wanders <ivor@iwanders.net>"]
edition = "2021"

# Disables error handling, prevents eh_personality requirement.
[profile.dev]
panic = "abort"
[profile.release]
panic = "abort"